language: c
matrix:
  include:
    - os: linux
      env:
        - PIP='sudo pip'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      env:
        - PYTHON=python3
env:
  global:
    - GOPATH: "$HOME/go"

before_script:
  - mkdir -p ~/bin
  - curl -L -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod +x ~/bin/gimme
  - gimme 1.12
  - source ~/.gimme/envs/go1.12.env
  - sh "./tiny-firmware/protob/ci-scripts/install-${TRAVIS_OS_NAME}.sh" ;
  # Define env vars for Linux builds
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    ls -l /usr/local/bin/protoc ;
    export CHECK_PATH="$(pwd)/check-0.12.0" ;
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CHECK_PATH}/src" ;
    export PATH="/usr/local/bin:$(pwd)/protoc/bin:$PATH" ;
    echo "PATH=$PATH";
    echo "PIP=$PIP";
    fi
  # Define env vars for osx builds
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    export CHECK_PATH="$(brew --prefix check)" ;
    export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${CHECK_PATH}/lib" ;
    fi
  # Install OS-specific test and build dependencies
  - eval "./ci-scripts/install-${TRAVIS_OS_NAME}.sh"
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export PATH="/opt/gcc-arm-none-eabi-6-2017-q2-update/bin:$PATH" ; fi
  # Install linters
  - make install-linters
  - git submodule update --remote
  # Install gcc 6 version, required for libskycoin
  #FIXME $TRAVIS_TAG != ''
  - if [[ $TRAVIS_TAG == 'osx' ]]; then
    make setup-libskycoin;
    ./tiny-firmware/vendor/libskycoin/ci-scripts/install-travis-gcc.sh;
    eval "CC=gcc-6 && CXX=g++-6";
    fi

script:
  - make check-protob
  - make lint
  - make -C tiny-firmware/protob build-c
  - FIRMWARE_SIGNATURE_PUB_KEY1=0241d51e593f681006f9f3c4a0ec744d459c960601b4ed770d979c32ace63b0a7a make test
  - make clean
  - make emulator
  - make clean
  - make bootloader-mem-protect
  - make bootloader-clean
  - make full-firmware
  - make clean

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

before_deploy:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      make release;
      VERSION_BOOTLOADER=$(cat tiny-firmware/bootloader/VERSION);
      ID_VENDOR=12602;
      ID_PRODUCT=1;
      export COMBINED_VERSION=${VERSION_BOOTLOADER}-${TRAVIS_TAG}-${ID_VENDOR}-${ID_PRODUCT}-1;
    else
      make release-emulator;
    fi

deploy:
- provider: releases
  api_key:
    secure: TODO generate it using travis CLI
  file:
  - releases/skywallet-firmware-${TRAVIS_TAG}.bin
  - releases/skywallet-bootloader-no-memory-protect-${VERSION_BOOTLOADER}.bin
  - releases/skywallet-full-mem-protect-${COMBINED_VERSION}.bin
  - releases/skywallet-bootloader-mem-protect-${VERSION_BOOTLOADER}.bin
  - releases/emulator-$(uname -s)-${TRAVIS_TAG}
  - releases/version.txt
  skip_cleanup: true
  draft: true
  on:
    repo: fibercrypto/skywallet-mcu
    tags: true
- provider: releases
  api_key:
    secure: TODO generate it using travis CLI
  file:
   - releases/emulator-$(uname -s)-${TRAVIS_TAG}
  skip_cleanup: true
  draft: true
  on:
    repo: fibercrypto/skywallet-mcu
    tags: true
    condition: $TRAVIS_OS_NAME = "osx"
